{{- if .Values.global.conf.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  routes:
  - kind: Rule
    match: Host(`{{ .Values.global.conf.ingress.host }}`)
    services:
    - name: {{ include "frontend.fullname" . }}
      port: {{ .Values.service.port }}
{{- end}}
