{{- if .Values.global.conf.ingress.enabled -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "backend.fullname" . }}

spec:
  routes:
  - kind: Rule
    match: Host(`{{ .Values.global.conf.ingress.host }}`) && PathPrefix(`/api`)
    services:
    - name: {{ include "backend.fullname" . }}
      port: {{ .Values.service.port }}
{{- end}}
